app = "dermascan-ai"
primary_region = "del"

[build]
  builder = "paketobuildpacks"

[env]
  PYTHONUNBUFFERED = "true"
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
